clc; clear; close all;

%% Настройки
Fs = 1000; % Частота дискретизации
chord_time = 0.5; % Длительность аккорда в секундах
note_time = 0.7; % Длительность нот в секундах
o = 0; % На сколько октав поднять

% Таблица частот нот
note_freq = struct(...
    'Z', 0.0, ...
    'B3', 246.94, 'F4', 349.23, 'Bb4', 466.16, ...
    'G3', 196.00, 'Bb3', 233.08, 'D5', 587.33, ...
    'C4', 261.63, 'Eb4', 311.13, 'Eb5', 622.254, ...
    'Ab', 207.65, 'D4', 293.66, 'G4', 392.00 ...
);
% B-dur/Gm*4/G*4/Cm*4;
% B-dur*4/Abmaj7*6/B-dur*2/Cm*4;
% Определяем аккорды и длительности (в долях)
chords = { % Adele - Rolling in the deep (Гитара)
    {{'Bb3','D4','F4'}, 4}, ...
    {{'G3','Bb3','D4'}, 4}, ...
    {{'G3','B3','D4'}, 4}, ...
    {{'C4','Eb4','G4'}, 4}, ...
    {{'B3','D4','F4'}, 4}, ...
    {{'Ab','C4','Eb4','G4'}, 6}, ...
    {{'B3','D4','F4'}, 2}, ...
    {{'C4','Eb4','G4'}, 4} ...
};

chords2 = { % Имперский марш
    {{'G4'}, 1}, ...
    {{'G4'}, 1}, ...
    {{'G4'}, 1}, ...
    {{'Eb4'}, 1}, ...
    {{'Z'}, 0.1}, ...
    {{'Bb4'}, 0.5}, ...
    {{'Z'}, 0.1}, ...
    {{'G4'}, 0.5}, ...
    {{'Z'}, 0.2}, ...
    {{'Eb4'}, 1}, ...
    {{'Z'}, 0.1}, ...
    {{'Bb4'}, 0.5}, ...
    {{'Z'}, 0.1}, ...
    {{'G4'}, 0.5}, ...
    {{'Z'}, 0.2}, ...
    {{'D5'}, 1}, ...
    {{'D5'}, 1}, ...
    {{'D5'}, 1}, ...
    {{'Eb5'}, 1}, ...
    {{'Bb4'}, 1}, ...
    {{'G4'}, 1}, ...
};


music = chords2;
if isequal(music, chords)
    time = chord_time;
else
    time = note_time;
end


signal = [];
for k = 1:length(music)
    notes = music{k}{1};
    duration = music{k}{2} * time;      
    t = 0:1/Fs:duration-1/Fs;
    
    chord_signal = zeros(1,length(t));
    for n = 1:length(notes)
        f = note_freq.(notes{n}) .* (2.^o);
        chord_signal = chord_signal + sin(2*pi*f*t);
    end
    pause_fraction = 0.01;
    pause_samples = round(pause_fraction * length(t));
    signal = [signal zeros(1, pause_samples)];
    signal = [signal chord_signal];
end

signal = signal / max(abs(signal));
figure('Position', [(1920-1920)/2, (1080-400)/2, 1920, 400]);
t = (0:length(signal)-1)/(Fs);
plot(t, signal);

disp(length(signal)/Fs)

player = audioplayer(signal, Fs);
play(player);
% audiowrite('melody2.wav', signal, Fs);
